### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by Terreii** [Terreii/shift-calendar-rt#47]
Rewrite the calendar in preact.

- [x] Rewrite the basics #37
- [x] Add PWA capabilities #37
- [x] Auto deploy #38
- [x] Add month selection #43
- [x] Add school holidays #45
- [x] Add a search for a day #46
- [x] Add option for displaying only one group #48
- [x] Add web-share button #49
